# Generated by Django 4.2.1 on 2023-07-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suv',
            name='litr',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
